/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.parking;

import org.junit.jupiter.api.Test;

class AppTest {

  @Test
  void appHasAGreeting() {
    ParkingSystem classUnderTest = new ParkingSystem();
  }
}
