/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.parking;

import org.junit.jupiter.api.Test;
import org.parking.building.Parking;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        Parking classUnderTest = new Parking();
    }
}
